module Test
{
    struct StTst
    {
	long   num_value;
	string str_value;
    };

    interface I { };
    typedef long long_array[5];
    typedef I i_array[10];
    typedef sequence<I> i_seq;
    
    union UTst switch (long)
    {
        case 0:	 long   num_value;
        case 1:  string str_value;
        default: StTst  struct_value;
	case 2:	 I if_value;
	case 3:  TypeCode ty_value;
	case 4: long_array la_value;
        case 5: i_array ia_value;
	case 6: i_seq is_value;
    
    };	
    
    interface ITst
    {
	void un_in    (in UTst    foo);
	void un_inout (inout UTst foo);
	void un_out   (out UTst   foo);
	UTst un_ret   ();
    };
};
