SUBDIRS := atomic_types inside_exception inside_struct with_interfaces with_string \
           with_array
	   # with_array does not work currently due to bad code generation

include ../../rules-delegate.mk
